server:
  port: 8082

spring:
  application:
    name: pubgateway-dispatcher

eureka:
  client:
    service-url:
      defaultZone: http://ec2-54-226-128-157.compute-1.amazonaws.com:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

logging:
  level:
    com.pubgateway.dispatcher: DEBUG
    org.springframework.cloud.openfeign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: PubGateway Dispatcher API
    description: Unified dispatcher service for publisher gateway plugins (Google, Meta, etc.)
    version: 1.0.0

